services:
  db:
    image: postgres:latest
    container_name: wallet-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5quever5
      POSTGRES_DB: walletdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d walletdb"]
      interval: 3s
      timeout: 3s
      retries: 5
    ports:
      - "5433:5432"
  
  wallet-service:
    build: .
    ports:
      - "8888:8888"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - config.env